# SwiftLint Configuration

# Paths to include/exclude
included:
  - Sources
  - Tests

excluded:
  - Pods
  - .build
  - .swiftpm

# Rules
disabled_rules:
  - trailing_whitespace
  
opt_in_rules:
  - empty_count
  - empty_string
  - force_unwrapping
  
# Rule customization
line_length:
  warning: 120
  error: 150
  
function_body_length:
  warning: 50
  error: 100

type_body_length:
  warning: 300
  error: 400

file_length:
  warning: 500
  error: 1000

identifier_name:
  min_length:
    warning: 2
  max_length:
    warning: 40
    error: 50