name: PR Check

on:
  pull_request:
    branches:
      - main
      - develop
  push:
    branches:
      - main
      - develop

jobs:
  check:
    runs-on: macos-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Install SwiftLint
        run: brew install swiftlint
      
      - name: Run SwiftLint
        run: |
          if [ -d "SwiftModern" ]; then
            swiftlint lint --path SwiftModern/
          else
            echo "SwiftModern directory not found, skipping SwiftLint"
          fi
      
      - name: Setup Swift
        uses: swift-actions/setup-swift@v2
        with:
          swift-version: "5.9"
      
      - name: Build
        run: |
          if [ -f "Package.swift" ]; then
            swift build
          else
            echo "No Package.swift found, skipping build"
          fi
      
      - name: Success
        run: echo "✅ All checks passed!"
